-- SPACE RESCUE — Supabase setup
-- Run this once in Supabase Dashboard → SQL Editor.

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(trim(player_name)) between 1 and 60),
  department text not null check (char_length(trim(department)) between 1 and 40),
  score integer not null check (score between -100000 and 100000),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

-- Public event game: players may submit scores.
drop policy if exists "Allow public score inserts" on public.scores;
create policy "Allow public score inserts"
on public.scores for insert
to anon, authenticated
with check (
  char_length(trim(player_name)) between 1 and 60
  and char_length(trim(department)) between 1 and 40
  and score between -100000 and 100000
);

-- Public event leaderboard: players may read the minimal score fields.
drop policy if exists "Allow public score reads" on public.scores;
create policy "Allow public score reads"
on public.scores for select
to anon, authenticated
using (true);

create index if not exists scores_department_idx on public.scores(department);
create index if not exists scores_created_at_idx on public.scores(created_at desc);

-- Optional: restrict departments by adding a check constraint later if your event
-- uses a fixed department list. The frontend currently offers:
-- CSE, AI&DS, ENTC, IT, MECH, CIVIL, E&TC
